/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        sentinel: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        navy: {
          800: '#0f172a',
          850: '#0b1120',
          900: '#090d16',
          950: '#030712',
        }
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      }
    },
  },
  plugins: [],
}

// Sync step: 9

// Sync step: 20

// Sync step: 9

// Sync step: 20

// Sync step: 31

// Sync step: 42

// Sync step: 53

// Sync step: 64

// Sync step: 82

// Sync step: 96

// Sync step: 110

// Sync step: 124

// Sync step: 138

// Sync step: 148

// Sync step: 173

// Sync step: 198

// Sync step: 222

// Sync step: 254

// Sync step: 286

// Sync step: 302

// Sync step: 340

// Sync step: 365

// Sync step: 9

// Sync step: 20

// Sync step: 31

// Sync step: 42

// Sync step: 53

// Sync step: 64

// Sync step: 82
