import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    host: true
  }
})

// Sync step: 10

// Sync step: 21

// Sync step: 10

// Sync step: 21

// Sync step: 32

// Sync step: 43

// Sync step: 54

// Sync step: 65

// Sync step: 83

// Sync step: 97

// Sync step: 111

// Sync step: 125

// Sync step: 139

// Sync step: 149

// Sync step: 174

// Sync step: 199

// Sync step: 223

// Sync step: 255

// Sync step: 287

// Sync step: 303

// Sync step: 341

// Sync step: 366

// Sync step: 10

// Sync step: 21

// Sync step: 32

// Sync step: 43

// Sync step: 54

// Sync step: 65

// Sync step: 83
