import random
from fastapi import APIRouter, HTTPException
from typing import Optional
from app.data_store import TRUCKS, DEPOTS, FPS_SHOPS

router = APIRouter(prefix="/api/trucks", tags=["Logistics Fleet & GPS Tracking"])

@router.get("")
def list_trucks(status_filter: Optional[str] = None):
    if status_filter:
        return [t for t in TRUCKS if t["status"].upper() == status_filter.upper()]
    return TRUCKS

@router.get("/{truck_id}")
def get_truck_details(truck_id: str):
    truck = next((t for t in TRUCKS if t["id"] == truck_id), None)
    if not truck:
        raise HTTPException(status_code=404, detail=f"Truck {truck_id} not found")
    
    depot = next((d for d in DEPOTS if d["id"] == truck["origin_depot"]), None)
    fps = next((f for f in FPS_SHOPS if f["id"] == truck["destination_fps"]), None)
    
    return {
        "telemetry": truck,
        "origin_depot_info": depot,
        "destination_fps_info": fps,
        "geofence_corridor": {
            "origin_coords": [depot["lat"], depot["lng"]] if depot else [21.1215, 79.0820],
            "destination_coords": [fps["lat"], fps["lng"]] if fps else [21.1550, 79.1120],
            "allowed_corridor_width_meters": 500,
            "current_corridor_deviation_meters": 3200 if truck.get("geofence_breach") else 45
        }
    }

@router.post("/{truck_id}/ping")
def update_truck_gps(truck_id: str, lat: Optional[float] = None, lng: Optional[float] = None, speed: Optional[float] = None):
    """
    Simulates a live GPS IoT ping from an in-transit delivery vehicle.
    """
    truck = next((t for t in TRUCKS if t["id"] == truck_id), None)
    if not truck:
        raise HTTPException(status_code=404, detail=f"Truck {truck_id} not found")
    
    if lat is not None and lng is not None:
        truck["current_lat"] = lat
        truck["current_lng"] = lng
    else:
        # Slight jitter for live telemetry animation
        truck["current_lat"] += random.uniform(-0.0005, 0.0005)
        truck["current_lng"] += random.uniform(-0.0005, 0.0005)
    
    if speed is not None:
        truck["speed_kmh"] = speed
    truck["last_ping"] = "Just now"
    
    return {"status": "SUCCESS", "updated_telemetry": truck}

# Sync step: 162

# Sync step: 187

# Sync step: 212

# Sync step: 236

# Sync step: 268

# Sync step: 316

# Sync step: 354

# Sync step: 382

# Sync step: 162

# Sync step: 187

# Sync step: 212

# Sync step: 236
