"""
PDS Sentinel AI - In-Memory High Performance Data Store
Pre-seeded with realistic PDS supply chain data for Nagpur District Hub.
"""

import random
from datetime import datetime, timedelta

# FCI / State Depots (Warehouses)
DEPOTS = [
    {
        "id": "DEPOT-NGP-01",
        "name": "FCI Central Depot - Ajni",
        "code": "FCI-AJNI-440003",
        "district": "Nagpur Urban",
        "lat": 21.1215,
        "lng": 79.0820,
        "capacity_mt": 15000,
        "current_stock_mt": {
            "rice": 6200,
            "wheat": 5400,
            "sugar": 850,
            "kerosene_kl": 220
        },
        "electronic_weighbridge_id": "WB-AJNI-01",
        "status": "OPERATIONAL"
    },
    {
        "id": "DEPOT-NGP-02",
        "name": "State Food Logistics Hub - Hingna MIDC",
        "code": "MSWC-HINGNA-440016",
        "district": "Nagpur Rural",
        "lat": 21.0945,
        "lng": 78.9890,
        "capacity_mt": 10000,
        "current_stock_mt": {
            "rice": 4100,
            "wheat": 3800,
            "sugar": 520,
            "kerosene_kl": 180
        },
        "electronic_weighbridge_id": "WB-HINGNA-02",
        "status": "OPERATIONAL"
    },
    {
        "id": "DEPOT-NGP-03",
        "name": "Kamptee Regional Buffer Silo",
        "code": "FCI-KAMPTEE-441002",
        "district": "Nagpur East",
        "lat": 21.2230,
        "lng": 79.1980,
        "capacity_mt": 8000,
        "current_stock_mt": {
            "rice": 3200,
            "wheat": 2900,
            "sugar": 310,
            "kerosene_kl": 90
        },
        "electronic_weighbridge_id": "WB-KAMPTEE-03",
        "status": "OPERATIONAL"
    }
]

# Fair Price Shops (FPS)
FPS_SHOPS = [
    {
        "id": "FPS-4101",
        "name": "Jai Durga Seva Sahakari Sanstha",
        "license_no": "MH/NGP/2018/0091",
        "dealer_name": "Rameshwar Patil",
        "phone": "+91 98230 11452",
        "address": "Sitabuldi Main Road, Ward 12, Nagpur",
        "district": "Nagpur Urban",
        "lat": 21.1465,
        "lng": 79.0832,
        "assigned_depot": "DEPOT-NGP-01",
        "beneficiaries_count": 1420,
        "monthly_quota_mt": {"rice": 14.2, "wheat": 17.0, "sugar": 1.4},
        "current_stock_mt": {"rice": 11.5, "wheat": 13.8, "sugar": 1.1},
        "opening_hours": "08:00 AM - 01:00 PM, 04:00 PM - 08:00 PM",
        "pos_device_id": "POS-NGP-4101",
        "weighing_scale_type": "Bluetooth Electronic (E-Weigh)",
        "trust_score": 96.5,
        "risk_level": "LOW",
        "inspection_status": "CLEARED",
        "tags": ["Verified", "Biometric Compliant", "Timely Distribution"]
    },
    {
        "id": "FPS-4102",
        "name": "Kisan Kranti Bachat Gat",
        "license_no": "MH/NGP/2016/0412",
        "dealer_name": "Suresh Chawla",
        "phone": "+91 98902 44319",
        "address": "Near Cotton Market, Itwari, Ward 24, Nagpur",
        "district": "Nagpur Urban",
        "lat": 21.1550,
        "lng": 79.1120,
        "assigned_depot": "DEPOT-NGP-01",
        "beneficiaries_count": 2150,
        "monthly_quota_mt": {"rice": 21.5, "wheat": 25.8, "sugar": 2.1},
        "current_stock_mt": {"rice": 3.2, "wheat": 4.1, "sugar": 0.4},
        "opening_hours": "Irregular (Complaints of frequent closure)",
        "pos_device_id": "POS-NGP-4102",
        "weighing_scale_type": "Manual Analog (Tamper Suspected)",
        "trust_score": 24.2,
        "risk_level": "CRITICAL",
        "inspection_status": "FLYING_SQUAD_RECOMMENDED",
        "tags": ["Diversion Risk", "Night Transactions", "Grievance Surge"]
    },
    {
        "id": "FPS-4103",
        "name": "Pragati Mahila PDS Kendra",
        "license_no": "MH/NGP/2020/1102",
        "dealer_name": "Sunita Deshmukh",
        "phone": "+91 94221 88301",
        "address": "Dharampeth Extension, Ward 08, Nagpur",
        "district": "Nagpur Urban",
        "lat": 21.1410,
        "lng": 79.0610,
        "assigned_depot": "DEPOT-NGP-01",
        "beneficiaries_count": 980,
        "monthly_quota_mt": {"rice": 9.8, "wheat": 11.7, "sugar": 0.98},
        "current_stock_mt": {"rice": 8.9, "wheat": 10.2, "sugar": 0.9},
        "opening_hours": "08:30 AM - 01:30 PM, 04:30 PM - 07:30 PM",
        "pos_device_id": "POS-NGP-4103",
        "weighing_scale_type": "Bluetooth Electronic (E-Weigh)",
        "trust_score": 98.2,
        "risk_level": "LOW",
        "inspection_status": "CLEARED",
        "tags": ["Model FPS", "100% Biometric Match", "Green Rated"]
    },
    {
        "id": "FPS-4104",
        "name": "Shri Ganesh Vitaran Kendra",
        "license_no": "MH/NGP/2019/0883",
        "dealer_name": "Vinod Agrawal",
        "phone": "+91 93710 99821",
        "address": "Kalamna Market Road, Ward 33, Nagpur",
        "district": "Nagpur East",
        "lat": 21.1730,
        "lng": 79.1520,
        "assigned_depot": "DEPOT-NGP-03",
        "beneficiaries_count": 1820,
        "monthly_quota_mt": {"rice": 18.2, "wheat": 21.8, "sugar": 1.8},
        "current_stock_mt": {"rice": 7.1, "wheat": 8.9, "sugar": 0.7},
        "opening_hours": "09:00 AM - 02:00 PM",
        "pos_device_id": "POS-NGP-4104",
        "weighing_scale_type": "Electronic Hybrid",
        "trust_score": 48.0,
        "risk_level": "MEDIUM",
        "inspection_status": "AUDIT_SCHEDULED",
        "tags": ["Weight Discrepancy", "Repeated Card Swiping"]
    },
    {
        "id": "FPS-4105",
        "name": "Bhimrao Ekta Sahakari Society",
        "license_no": "MH/NGP/2021/0149",
        "dealer_name": "Prakash Meshram",
        "phone": "+91 97633 45190",
        "address": "Indora Chowk, Ward 18, North Nagpur",
        "district": "Nagpur Urban",
        "lat": 21.1750,
        "lng": 79.0980,
        "assigned_depot": "DEPOT-NGP-01",
        "beneficiaries_count": 1640,
        "monthly_quota_mt": {"rice": 16.4, "wheat": 19.6, "sugar": 1.6},
        "current_stock_mt": {"rice": 14.1, "wheat": 16.9, "sugar": 1.4},
        "opening_hours": "08:00 AM - 01:00 PM, 03:30 PM - 07:30 PM",
        "pos_device_id": "POS-NGP-4105",
        "weighing_scale_type": "Bluetooth Electronic (E-Weigh)",
        "trust_score": 92.4,
        "risk_level": "LOW",
        "inspection_status": "CLEARED",
        "tags": ["Verified", "Zero Stock Diversion"]
    },
    {
        "id": "FPS-4106",
        "name": "Hingna Rural Jan Suvidha",
        "license_no": "MH/NGP/2015/0024",
        "dealer_name": "Mahesh Bhende",
        "phone": "+91 98229 33718",
        "address": "Near Gram Panchayat, Hingna Village",
        "district": "Nagpur Rural",
        "lat": 21.0820,
        "lng": 78.9640,
        "assigned_depot": "DEPOT-NGP-02",
        "beneficiaries_count": 1280,
        "monthly_quota_mt": {"rice": 12.8, "wheat": 15.3, "sugar": 1.28},
        "current_stock_mt": {"rice": 4.5, "wheat": 5.2, "sugar": 0.5},
        "opening_hours": "10:00 AM - 05:00 PM",
        "pos_device_id": "POS-NGP-4106",
        "weighing_scale_type": "Electronic",
        "trust_score": 38.5,
        "risk_level": "HIGH",
        "inspection_status": "WARNING_ISSUED",
        "tags": ["Ghost Beneficiary Anomaly", "Frequent Offline Sync"]
    },
    {
        "id": "FPS-4107",
        "name": "Sadar Peoples Provision Store",
        "license_no": "MH/NGP/2017/0552",
        "dealer_name": "Harish Motwani",
        "phone": "+91 99231 66209",
        "address": "Residency Road, Sadar, Nagpur",
        "district": "Nagpur Urban",
        "lat": 21.1610,
        "lng": 79.0780,
        "assigned_depot": "DEPOT-NGP-01",
        "beneficiaries_count": 1100,
        "monthly_quota_mt": {"rice": 11.0, "wheat": 13.2, "sugar": 1.1},
        "current_stock_mt": {"rice": 9.8, "wheat": 11.5, "sugar": 0.95},
        "opening_hours": "09:00 AM - 01:00 PM, 04:00 PM - 08:00 PM",
        "pos_device_id": "POS-NGP-4107",
        "weighing_scale_type": "Bluetooth Electronic (E-Weigh)",
        "trust_score": 89.0,
        "risk_level": "LOW",
        "inspection_status": "CLEARED",
        "tags": ["Compliant", "High Digital Adoption"]
    },
    {
        "id": "FPS-4108",
        "name": "Mihan Growth Zone Ration Corner",
        "license_no": "MH/NGP/2022/0319",
        "dealer_name": "Abhay Tiwari",
        "phone": "+91 91580 44921",
        "address": "Wardha Road, Khapri, Nagpur",
        "district": "Nagpur Rural",
        "lat": 21.0480,
        "lng": 79.0550,
        "assigned_depot": "DEPOT-NGP-02",
        "beneficiaries_count": 890,
        "monthly_quota_mt": {"rice": 8.9, "wheat": 10.6, "sugar": 0.89},
        "current_stock_mt": {"rice": 7.4, "wheat": 8.8, "sugar": 0.72},
        "opening_hours": "08:30 AM - 06:30 PM",
        "pos_device_id": "POS-NGP-4108",
        "weighing_scale_type": "Electronic",
        "trust_score": 91.0,
        "risk_level": "LOW",
        "inspection_status": "CLEARED",
        "tags": ["Verified", "New Biometric Terminal"]
    }
]

# GPS-Tracked Logistics Fleet (Supply Delivery Trucks)
TRUCKS = [
    {
        "id": "TRK-MH31-8820",
        "reg_no": "MH-31-CV-8820",
        "driver_name": "Sanjay Gaikwad",
        "driver_phone": "+91 98810 55140",
        "origin_depot": "DEPOT-NGP-01",
        "destination_fps": "FPS-4102",
        "consignment_no": "CNS-2026-08-9941",
        "cargo": {"commodity": "Food Grain (Wheat & Rice)", "dispatched_mt": 12.0},
        "current_lat": 21.1512,
        "current_lng": 79.1350,
        "speed_kmh": 0,
        "heading": "NE",
        "status": "ANOMALY_ROUTE_DEVIATION",
        "geofence_breach": True,
        "seal_status": "E-LOCK_TAMPERED",
        "expected_arrival": "14:30 (Delayed by 2h 15m)",
        "last_ping": "1 min ago",
        "deviation_duration_min": 135,
        "unauthorized_stop_location": "Pardi Private Flour Mill Estate",
        "weight_at_dispatch_mt": 12.0,
        "current_estimated_weight_mt": 7.8,
        "anomaly_reason": "Truck stationary in unauthorized commercial milling cluster for 2h15m. Suspected 4.2 MT offloading."
    },
    {
        "id": "TRK-MH31-4921",
        "reg_no": "MH-31-AZ-4921",
        "driver_name": "Abdul Latif",
        "driver_phone": "+91 97640 12899",
        "origin_depot": "DEPOT-NGP-01",
        "destination_fps": "FPS-4101",
        "consignment_no": "CNS-2026-08-9942",
        "cargo": {"commodity": "Rice & Sugar", "dispatched_mt": 9.5},
        "current_lat": 21.1340,
        "current_lng": 79.0810,
        "speed_kmh": 28,
        "heading": "N",
        "status": "ON_ROUTE_NORMAL",
        "geofence_breach": False,
        "seal_status": "E-LOCK_INTACT",
        "expected_arrival": "On Time (in 12 min)",
        "last_ping": "15 sec ago",
        "deviation_duration_min": 0,
        "unauthorized_stop_location": None,
        "weight_at_dispatch_mt": 9.5,
        "current_estimated_weight_mt": 9.5,
        "anomaly_reason": None
    },
    {
        "id": "TRK-MH40-1104",
        "reg_no": "MH-40-BL-1104",
        "driver_name": "Devidas Raut",
        "driver_phone": "+91 94234 90123",
        "origin_depot": "DEPOT-NGP-02",
        "destination_fps": "FPS-4106",
        "consignment_no": "CNS-2026-08-9943",
        "cargo": {"commodity": "Wheat", "dispatched_mt": 10.0},
        "current_lat": 21.0880,
        "current_lng": 78.9750,
        "speed_kmh": 32,
        "heading": "SW",
        "status": "ON_ROUTE_NORMAL",
        "geofence_breach": False,
        "seal_status": "E-LOCK_INTACT",
        "expected_arrival": "On Time (in 8 min)",
        "last_ping": "30 sec ago",
        "deviation_duration_min": 0,
        "unauthorized_stop_location": None,
        "weight_at_dispatch_mt": 10.0,
        "current_estimated_weight_mt": 10.0,
        "anomaly_reason": None
    },
    {
        "id": "TRK-MH31-7712",
        "reg_no": "MH-31-EQ-7712",
        "driver_name": "Nitin Wandhare",
        "driver_phone": "+91 93255 77102",
        "origin_depot": "DEPOT-NGP-03",
        "destination_fps": "FPS-4104",
        "consignment_no": "CNS-2026-08-9944",
        "cargo": {"commodity": "Fortified Rice", "dispatched_mt": 8.0},
        "current_lat": 21.1920,
        "current_lng": 79.1720,
        "speed_kmh": 0,
        "heading": "S",
        "status": "EXTENDED_HALT",
        "geofence_breach": False,
        "seal_status": "E-LOCK_INTACT",
        "expected_arrival": "Delayed (25 min halt on NH-53)",
        "last_ping": "45 sec ago",
        "deviation_duration_min": 25,
        "unauthorized_stop_location": "Toll Plaza Highway Rest",
        "weight_at_dispatch_mt": 8.0,
        "current_estimated_weight_mt": 8.0,
        "anomaly_reason": "Minor stationary halt > 20 mins without designated checkpoint flag."
    }
]

# Active Fraud & Risk Alerts generated by PDS Sentinel Decision Engine
ALERTS = [
    {
        "id": "ALT-2026-0801",
        "title": "Severe Stock Diversion & Weight Mismatch Detected",
        "severity": "CRITICAL",
        "fps_id": "FPS-4102",
        "fps_name": "Kisan Kranti Bachat Gat",
        "truck_id": "TRK-MH31-8820",
        "timestamp": "2026-08-17T15:42:00",
        "mste_trust_score": 24.2,
        "estimated_leakage_mt": 4.2,
        "estimated_fraud_value_inr": 168000,
        "evidence_chain": [
            {"source": "GPS Telemetry", "detail": "135-min unauthorized halt at Pardi Private Flour Mill (Lat 21.1512, Lng 79.1350)"},
            {"source": "Electronic Weighbridge", "detail": "Dispatch: 12.0 MT vs In-Transit Telemetry: 7.8 MT (-4.2 MT discrepancy)"},
            {"source": "POS Anomaly Detector", "detail": "46 ration card sweeps recorded between 01:15 AM - 03:30 AM with zero biometric auth"},
            {"source": "Citizen Grievances", "detail": "18 complaints in past 48 hrs stating 'Dealer reported stock exhausted within 2 days'"}
        ],
        "shap_breakdown": {
            "weight_discrepancy": 38.5,
            "gps_route_deviation": 27.2,
            "night_pos_transactions": 19.1,
            "citizen_complaint_surge": 15.2
        },
        "ai_recommended_action": "Dispatch Vigilance Flying Squad immediately, freeze monthly quota allocation, and divert incoming consignments to verified FPS-4103.",
        "status": "ACTION_REQUIRED",
        "assigned_squad": None,
        "action_history": []
    },
    {
        "id": "ALT-2026-0802",
        "title": "Suspected Ghost Ration Cards / Off-Hours Transaction Burst",
        "severity": "HIGH",
        "fps_id": "FPS-4106",
        "fps_name": "Hingna Rural Jan Suvidha",
        "truck_id": None,
        "timestamp": "2026-08-17T14:10:00",
        "mste_trust_score": 38.5,
        "estimated_leakage_mt": 1.8,
        "estimated_fraud_value_inr": 72000,
        "evidence_chain": [
            {"source": "POS Anomaly Detector", "detail": "Velocity of 1 transaction every 6 seconds on POS-NGP-4106 with identical OTP timestamps"},
            {"source": "Aadhaar Audit Log", "detail": "14 beneficiary accounts flagged deceased or migrated in NFSA database"},
            {"source": "Stock Ledger", "detail": "Theoretical closing balance 6.3 MT, reported stock 4.5 MT"}
        ],
        "shap_breakdown": {
            "transaction_velocity": 42.0,
            "ghost_beneficiary_match": 31.5,
            "stock_balance_gap": 18.0,
            "complaint_sentiment": 8.5
        },
        "ai_recommended_action": "Issue digital show-cause notice, enforce mandatory Iris/Biometric verification at point of sale.",
        "status": "ACTION_REQUIRED",
        "assigned_squad": None,
        "action_history": []
    },
    {
        "id": "ALT-2026-0803",
        "title": "Under-Weighing Pattern Detected (E-Scale Calibration Variance)",
        "severity": "MEDIUM",
        "fps_id": "FPS-4104",
        "fps_name": "Shri Ganesh Vitaran Kendra",
        "truck_id": None,
        "timestamp": "2026-08-17T12:05:00",
        "mste_trust_score": 48.0,
        "estimated_leakage_mt": 0.9,
        "estimated_fraud_value_inr": 36000,
        "evidence_chain": [
            {"source": "Citizen Grievances", "detail": "8 citizen complaints of receiving 4.2 kg instead of entitled 5.0 kg per unit"},
            {"source": "E-Weigh Telemetry", "detail": "Scale tare value locked at -350 grams over 180 consecutive transactions"}
        ],
        "shap_breakdown": {
            "scale_calibration_bias": 45.0,
            "citizen_complaints": 35.0,
            "quota_variance": 20.0
        },
        "ai_recommended_action": "Deploy Weights & Measures Inspector for surprise electronic scale re-calibration.",
        "status": "IN_REVIEW",
        "assigned_squad": "Inspector Team 4 - East Zone",
        "action_history": [
            {"timestamp": "2026-08-17T13:00:00", "action": "Inspector Team 4 notified for surprise calibration check."}
        ]
    }
]

# Citizen Grievances / Complaints with Multilingual Support (English, Hindi, Marathi)
COMPLAINTS = [
    {
        "id": "GRV-2026-1049",
        "fps_id": "FPS-4102",
        "fps_name": "Kisan Kranti Bachat Gat",
        "citizen_name": "Sunil Kamble",
        "card_no": "RC-MH-2710-8849",
        "language": "mr",
        "original_text": "दुकानदार सांगतो धान्य संपले आहे, पण रात्री ट्रक मधून धान्य खासगी गिरणीत नेताना पाहिले. आम्हाला या महिन्याचा कोटा मिळाला नाही.",
        "translated_text": "Dealer says grain is finished, but we saw grain being loaded from truck into a private mill at night. We have not received our quota this month.",
        "category": "STOCK_DIVERSION",
        "sentiment": "NEGATIVE",
        "urgency": "HIGH",
        "created_at": "2026-08-17T11:20:00",
        "status": "VERIFIED_AI_ALERT",
        "verified_with_mste": True
    },
    {
        "id": "GRV-2026-1050",
        "fps_id": "FPS-4102",
        "fps_name": "Kisan Kranti Bachat Gat",
        "citizen_name": "Amina Bano",
        "card_no": "RC-MH-2710-3321",
        "language": "hi",
        "original_text": "राशन डीलर फिंगरप्रिंट लगवा लेता है और बोलता है सर्वर डाउन है राशन कल आना। 3 दिन से चक्कर लगा रहे हैं राशन नहीं दिया।",
        "translated_text": "Ration dealer takes fingerprint and claims server is down and to come tomorrow. Making rounds for 3 days, no ration given.",
        "category": "BIOMETRIC_DENIAL",
        "sentiment": "NEGATIVE",
        "urgency": "HIGH",
        "created_at": "2026-08-17T12:05:00",
        "status": "VERIFIED_AI_ALERT",
        "verified_with_mste": True
    },
    {
        "id": "GRV-2026-1051",
        "fps_id": "FPS-4104",
        "fps_name": "Shri Ganesh Vitaran Kendra",
        "citizen_name": "Rajendra Sharma",
        "card_no": "RC-MH-2710-9912",
        "language": "en",
        "original_text": "The electronic weighing scale is showing 5kg on screen but when we weighed it at home grocery store it was only 4.2kg. Overcharging extra 5 rupees per kg.",
        "translated_text": "The electronic weighing scale is showing 5kg on screen but when we weighed it at home grocery store it was only 4.2kg. Overcharging extra 5 rupees per kg.",
        "category": "UNDER_WEIGHING",
        "sentiment": "NEGATIVE",
        "urgency": "MEDIUM",
        "created_at": "2026-08-17T09:40:00",
        "status": "UNDER_INVESTIGATION",
        "verified_with_mste": True
    },
    {
        "id": "GRV-2026-1052",
        "fps_id": "FPS-4101",
        "fps_name": "Jai Durga Seva Sahakari Sanstha",
        "citizen_name": "Pooja Meshram",
        "card_no": "RC-MH-2710-4410",
        "language": "mr",
        "original_text": "या दुकानावर सर्व धान्य वेळेवर आणि योग्य वजनाने मिळाले. सेवा अतिशय चांगली आहे.",
        "translated_text": "All grain received on time and with exact weight at this shop. Service is very good.",
        "category": "APPRECIATION_FEEDBACK",
        "sentiment": "POSITIVE",
        "urgency": "LOW",
        "created_at": "2026-08-17T10:15:00",
        "status": "RESOLVED",
        "verified_with_mste": False
    }
]

# Sample Beneficiary Ration Cards for Citizen Portal Search
BENEFICIARIES = {
    "RC-MH-2710-8849": {
        "card_no": "RC-MH-2710-8849",
        "card_type": "PHH (Priority Household - Yellow)",
        "head_of_family": "Sunil Vitthal Kamble",
        "family_members": 4,
        "assigned_fps_id": "FPS-4102",
        "district": "Nagpur Urban",
        "monthly_quota": {
            "rice_kg": 12.0,
            "wheat_kg": 8.0,
            "sugar_kg": 1.0,
            "subsidized_price_total_inr": 65
        },
        "current_month_status": {
            "month": "August 2026",
            "rice_lifted_kg": 0.0,
            "wheat_lifted_kg": 0.0,
            "sugar_lifted_kg": 0.0,
            "status": "PENDING_LIFTING",
            "warning": "Assigned shop (FPS-4102) has flagged stock diversion alerts. Verified alternative shops available nearby."
        }
    },
    "RC-MH-2710-4410": {
        "card_no": "RC-MH-2710-4410",
        "card_type": "AAY (Antyodaya Anna Yojana - Pink)",
        "head_of_family": "Pooja Suresh Meshram",
        "family_members": 5,
        "assigned_fps_id": "FPS-4101",
        "district": "Nagpur Urban",
        "monthly_quota": {
            "rice_kg": 20.0,
            "wheat_kg": 15.0,
            "sugar_kg": 2.0,
            "subsidized_price_total_inr": 70
        },
        "current_month_status": {
            "month": "August 2026",
            "rice_lifted_kg": 20.0,
            "wheat_lifted_kg": 15.0,
            "sugar_lifted_kg": 2.0,
            "status": "FULLY_LIFTED",
            "warning": None
        }
    },
    "RC-MH-2710-3321": {
        "card_no": "RC-MH-2710-3321",
        "card_type": "PHH (Priority Household - Yellow)",
        "head_of_family": "Amina Bano Sheikh",
        "family_members": 3,
        "assigned_fps_id": "FPS-4102",
        "district": "Nagpur Urban",
        "monthly_quota": {
            "rice_kg": 9.0,
            "wheat_kg": 6.0,
            "sugar_kg": 1.0,
            "subsidized_price_total_inr": 50
        },
        "current_month_status": {
            "month": "August 2026",
            "rice_lifted_kg": 0.0,
            "wheat_lifted_kg": 0.0,
            "sugar_lifted_kg": 0.0,
            "status": "DENIED_BIOMETRIC_ERROR",
            "warning": "High anomaly score detected at shop. Immediate complaint redressal active."
        }
    }
}

DATA_STORE = {
    "fps": FPS_SHOPS,
    "trucks": TRUCKS,
    "alerts": ALERTS,
    "complaints": COMPLAINTS,
    "depots": DEPOTS,
    "beneficiaries": BENEFICIARIES,
    "stats": {
        "impact_metrics": {
            "grain_saved_tons": 148.5,
            "public_funds_protected_inr": 5940000,
            "diversion_cases_stopped": 19,
            "diversion_detection_accuracy_pct": 98.4,
            "response_time_minutes": 4.5
        },
        "system_health": {
            "model_precision_percent": 98.4,
            "latency_ms": 12,
            "uptime_pct": 99.98
        }
    }
}


# Sync step: 71

# Sync step: 85

# Sync step: 99

# Sync step: 113

# Sync step: 127

# Sync step: 151

# Sync step: 176

# Sync step: 201

# Sync step: 225

# Sync step: 257

# Sync step: 289

# Sync step: 305

# Sync step: 343

# Sync step: 371

# Sync step: 71
