"""
PDS Sentinel AI - Master FastAPI Application
AI-Driven Predictive Prevention, Decision Copilot, and Multi-Source Trust Engine
for Indian Public Distribution System (PDS)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routers import stats, fps, trucks, alerts, citizen, simulation, copilot

app = FastAPI(
    title="PDS Sentinel AI Decision Engine",
    description="Predictive Prevention, Multi-Source Trust Engine, Explainable AI, and Digital Twin for Public Distribution Systems.",
    version="2.0.0"
)

# Enable CORS for Frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include Routers
app.include_router(stats.router)
app.include_router(fps.router)
app.include_router(trucks.router)
app.include_router(alerts.router)
app.include_router(citizen.router)
app.include_router(simulation.router)
app.include_router(copilot.router)

@app.get("/")
def root_info():
    return {
        "platform": "PDS Sentinel AI",
        "team": "Pragati 2.0",
        "status": "ONLINE",
        "description": "AI-Powered PDS Governance, Anomaly Prevention, and Decision Support Engine",
        "endpoints": {
            "stats": "/api/stats",
            "fps_list": "/api/fps",
            "trucks": "/api/trucks",
            "alerts": "/api/alerts",
            "citizen_portal": "/api/citizen",
            "simulation": "/api/simulation",
            "copilot": "/api/copilot/chat"
        }
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)

# Sync step: 1

# Sync step: 12

# Sync step: 1

# Sync step: 12

# Sync step: 23

# Sync step: 34

# Sync step: 45

# Sync step: 56

# Sync step: 67

# Sync step: 72

# Sync step: 86

# Sync step: 100

# Sync step: 114

# Sync step: 128

# Sync step: 152

# Sync step: 177

# Sync step: 202

# Sync step: 226

# Sync step: 258

# Sync step: 306

# Sync step: 344

# Sync step: 372

# Sync step: 1

# Sync step: 12

# Sync step: 23

# Sync step: 34

# Sync step: 45

# Sync step: 56
