"""
Machine Learning Anomaly Detection & SHAP Explainability Engine
Uses Scikit-learn Isolation Forest with feature attribution calculations.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from typing import Dict, Any, List

class MLAnomalyEngine:
    def __init__(self):
        # Feature columns:
        # 1. weight_discrepancy_kg
        # 2. gps_route_deviation_minutes
        # 3. night_hours_pos_transactions_count
        # 4. transaction_velocity_seconds_per_tx
        # 5. complaints_count_last_48h
        # 6. stock_depletion_velocity_ratio
        
        self.feature_names = [
            "weight_discrepancy_kg",
            "gps_route_deviation_minutes",
            "night_pos_transactions",
            "pos_velocity_speedup",
            "complaint_surge_count",
            "stock_depletion_variance"
        ]
        
        self.model = IsolationForest(
            n_estimators=100,
            contamination=0.15,
            random_state=42
        )
        self._fit_synthetic_baseline()

    def _fit_synthetic_baseline(self):
        # Generate baseline normal distribution for standard compliant Fair Price Shops
        np.random.seed(42)
        normal_samples = np.random.normal(
            loc=[15, 5, 0, 90, 0.2, 1.0],
            scale=[10, 5, 0.5, 20, 0.5, 0.1],
            size=(500, 6)
        )
        normal_samples = np.clip(normal_samples, a_min=0, a_max=None)
        
        # Inject known anomalous patterns (diversion, ghost cards, mill stops)
        anomaly_samples = np.array([
            [4200, 135, 46, 6, 18, 4.2],  # FPS-4102 severe diversion
            [1800, 0, 68, 4, 14, 2.8],    # FPS-4106 ghost card burst
            [900, 15, 2, 85, 8, 1.3],     # FPS-4104 under-weighing
            [3500, 90, 30, 12, 12, 3.5],  # synthetic diversion
            [2200, 60, 25, 8, 9, 2.5]     # synthetic ghost carding
        ])
        
        X_train = np.vstack([normal_samples, anomaly_samples])
        self.model.fit(X_train)

    def predict_fps_risk(self, features: Dict[str, float]) -> Dict[str, Any]:
        """
        Takes raw feature metrics for an FPS, runs Isolation Forest scoring,
        and computes SHAP-inspired feature attribution percentages.
        """
        vec = np.array([[
            features.get("weight_discrepancy_kg", 0.0),
            features.get("gps_route_deviation_minutes", 0.0),
            features.get("night_pos_transactions", 0.0),
            features.get("pos_velocity_speedup", 90.0), # lower seconds = higher velocity anomaly
            features.get("complaint_surge_count", 0.0),
            features.get("stock_depletion_variance", 1.0)
        ]])
        
        # Isolation Forest decision function score (lower score = higher anomaly)
        raw_score = float(self.model.decision_function(vec)[0])
        # Convert to Anomaly Probability (0.0 to 1.0)
        anomaly_probability = round(float(1.0 / (1.0 + np.exp(raw_score * 4.0))), 3)
        is_anomaly = bool(anomaly_probability > 0.55)

        # Compute SHAP-style attribution (normalized relative impact of each feature)
        # Normal reference baselines
        baseline_means = np.array([15.0, 5.0, 0.0, 90.0, 0.2, 1.0])
        diff = np.abs(vec[0] - baseline_means)
        
        # Scale factors to balance metric ranges (kg vs minutes vs counts)
        weights = np.array([1.0 / 100.0, 1.0 / 10.0, 1.5, 1.0 / 5.0, 3.0, 10.0])
        contributions = diff * weights
        total_contrib = np.sum(contributions) or 1.0
        
        normalized_shap = {
            "weight_discrepancy": round(float((contributions[0] / total_contrib) * 100), 1),
            "gps_route_deviation": round(float((contributions[1] / total_contrib) * 100), 1),
            "night_pos_transactions": round(float((contributions[2] / total_contrib) * 100), 1),
            "transaction_velocity": round(float((contributions[3] / total_contrib) * 100), 1),
            "citizen_complaint_surge": round(float((contributions[4] / total_contrib) * 100), 1),
            "stock_depletion_variance": round(float((contributions[5] / total_contrib) * 100), 1)
        }

        # Human-readable evidence explanation
        evidence_summary = []
        if features.get("weight_discrepancy_kg", 0) > 500:
            evidence_summary.append(f"Electronic weighbridge mismatch of {features['weight_discrepancy_kg']} kg detected.")
        if features.get("gps_route_deviation_minutes", 0) > 30:
            evidence_summary.append(f"Supply truck had {features['gps_route_deviation_minutes']} mins unscheduled off-route halt.")
        if features.get("night_pos_transactions", 0) > 10:
            evidence_summary.append(f"Unusual surge of {features['night_pos_transactions']} POS transactions between 00:00 - 05:00 AM.")
        if features.get("complaint_surge_count", 0) > 5:
            evidence_summary.append(f"Cluster of {features['complaint_surge_count']} citizen grievances reporting ration denial/hoarding.")

        return {
            "is_anomaly": is_anomaly,
            "anomaly_probability": anomaly_probability,
            "raw_decision_score": round(raw_score, 4),
            "shap_feature_breakdown": normalized_shap,
            "evidence_summary": evidence_summary
        }

# Global singleton
ml_engine = MLAnomalyEngine()

# Sync step: 73

# Sync step: 87

# Sync step: 101

# Sync step: 115

# Sync step: 129

# Sync step: 153

# Sync step: 178

# Sync step: 203

# Sync step: 227

# Sync step: 259

# Sync step: 307

# Sync step: 345

# Sync step: 373

# Sync step: 73

# Sync step: 87

# Sync step: 101

# Sync step: 115

# Sync step: 129

# Sync step: 153

# Sync step: 178

# Sync step: 203

# Sync step: 227

# Sync step: 259

# Sync step: 307
