"""
Multi-Source Trust Engine (MSTE) for PDS Sentinel AI.
Cross-verifies 5 independent data streams to compute dynamic Fair Price Shop Trust Scores (0 - 100)
and assigns actionable Risk Tiers (LOW, MEDIUM, HIGH, CRITICAL).
"""

from typing import Dict, Any

class MultiSourceTrustEngine:
    """
    Combines:
    1. GPS Fleet Route Integrity (Weight: 25%)
    2. Electronic Weighbridge Discrepancy (Weight: 30%)
    3. POS Transaction Velocity & Off-hours Behaviour (Weight: 20%)
    4. Stock Balance Reconciliation (Weight: 15%)
    5. Citizen Grievance & NLP Sentiment Density (Weight: 10%)
    """
    
    WEIGHTS = {
        "weighbridge": 0.30,
        "gps_logistics": 0.25,
        "pos_transactions": 0.20,
        "stock_reconciliation": 0.15,
        "citizen_complaints": 0.10
    }

    @classmethod
    def evaluate_fps(cls, fps_data: Dict[str, Any], truck_data: list = None, complaints: list = None) -> Dict[str, Any]:
        """
        Evaluate a single FPS and return score breakdown, risk level, and recommendations.
        """
        fps_id = fps_data["id"]
        
        # 1. Weighbridge sub-score (0 - 100)
        # Check scale type and historic weight difference
        if "Manual" in fps_data.get("weighing_scale_type", ""):
            weigh_subscore = 35.0
        elif fps_data.get("trust_score", 100) < 50:
            weigh_subscore = 30.0
        else:
            weigh_subscore = 98.0
            
        # 2. GPS Fleet Subscore
        # Check if incoming truck had geofence breach or unauthorized stop
        relevant_trucks = [t for t in (truck_data or []) if t.get("destination_fps") == fps_id]
        if relevant_trucks:
            t = relevant_trucks[0]
            if t.get("geofence_breach") or t.get("status") == "ANOMALY_ROUTE_DEVIATION":
                gps_subscore = 15.0
            elif t.get("status") == "EXTENDED_HALT":
                gps_subscore = 65.0
            else:
                gps_subscore = 99.0
        else:
            gps_subscore = 90.0 if fps_data.get("risk_level") == "LOW" else 50.0

        # 3. POS Transaction Behavior Subscore
        if "Night Transactions" in fps_data.get("tags", []) or "Repeated Card Swiping" in fps_data.get("tags", []):
            pos_subscore = 30.0
        elif "Ghost Beneficiary" in str(fps_data.get("tags", [])):
            pos_subscore = 40.0
        else:
            pos_subscore = 95.0

        # 4. Stock Reconciliation Subscore
        monthly = fps_data.get("monthly_quota_mt", {}).get("rice", 10) + fps_data.get("monthly_quota_mt", {}).get("wheat", 10)
        curr = fps_data.get("current_stock_mt", {}).get("rice", 5) + fps_data.get("current_stock_mt", {}).get("wheat", 5)
        stock_ratio = curr / monthly if monthly > 0 else 0.5
        if stock_ratio < 0.20 and "Diversion Risk" in fps_data.get("tags", []):
            stock_subscore = 25.0
        else:
            stock_subscore = 92.0

        # 5. Citizen Grievance Density Subscore
        fps_complaints = [c for c in (complaints or []) if c.get("fps_id") == fps_id and c.get("category") in ["STOCK_DIVERSION", "BIOMETRIC_DENIAL", "UNDER_WEIGHING"]]
        if len(fps_complaints) >= 2:
            complaint_subscore = 20.0
        elif len(fps_complaints) == 1:
            complaint_subscore = 60.0
        else:
            complaint_subscore = 98.0

        # Composite MSTE Trust Score
        total_trust_score = round(
            (weigh_subscore * cls.WEIGHTS["weighbridge"]) +
            (gps_subscore * cls.WEIGHTS["gps_logistics"]) +
            (pos_subscore * cls.WEIGHTS["pos_transactions"]) +
            (stock_subscore * cls.WEIGHTS["stock_reconciliation"]) +
            (complaint_subscore * cls.WEIGHTS["citizen_complaints"]),
            1
        )

        # Risk Classification
        if total_trust_score >= 80.0:
            risk_level = "LOW"
            recommended_action = "Standard Automated Monitoring; No intervention required."
        elif total_trust_score >= 55.0:
            risk_level = "MEDIUM"
            recommended_action = "Schedule routine digital audit and verify scale calibration."
        elif total_trust_score >= 35.0:
            risk_level = "HIGH"
            recommended_action = "Issue digital show-cause notice and deploy Sector Inspector for physical verification."
        else:
            risk_level = "CRITICAL"
            recommended_action = "Immediate Vigilance Flying Squad deployment; temporarily lock quota release and divert stock to nearest verified FPS."

        return {
            "fps_id": fps_id,
            "composite_trust_score": total_trust_score,
            "risk_level": risk_level,
            "subscores": {
                "weighbridge_integrity": weigh_subscore,
                "gps_route_compliance": gps_subscore,
                "pos_transaction_regularity": pos_subscore,
                "stock_reconciliation": stock_subscore,
                "citizen_satisfaction": complaint_subscore
            },
            "weights": cls.WEIGHTS,
            "recommended_action": recommended_action
        }

# Sync step: 74

# Sync step: 88

# Sync step: 102

# Sync step: 116

# Sync step: 130

# Sync step: 154

# Sync step: 179

# Sync step: 204

# Sync step: 228

# Sync step: 260

# Sync step: 308

# Sync step: 346

# Sync step: 374

# Sync step: 74

# Sync step: 88

# Sync step: 102

# Sync step: 116

# Sync step: 130

# Sync step: 154

# Sync step: 179

# Sync step: 204
