"""
Digital Twin Simulation Engine for PDS Sentinel AI.
Simulates real-time supply chain disruptions and tests automated mitigation strategies.
"""

from typing import Dict, Any
from app.data_store import TRUCKS, FPS_SHOPS, ALERTS

class DigitalTwinSimulator:
    @classmethod
    def run_scenario(cls, scenario_type: str) -> Dict[str, Any]:
        if scenario_type == "DIVERSION_FLOUR_MILL":
            # Update truck state to active diversion
            for t in TRUCKS:
                if t["id"] == "TRK-MH31-8820":
                    t["status"] = "ANOMALY_ROUTE_DEVIATION"
                    t["geofence_breach"] = True
                    t["seal_status"] = "E-LOCK_TAMPERED"
                    t["speed_kmh"] = 0
                    t["deviation_duration_min"] = 145
                    t["current_estimated_weight_mt"] = 7.5
                    t["anomaly_reason"] = "LIVE ALERT: Truck stationary at private milling unit. Weight reduced by 4.5 MT."
            
            # Update FPS-4102
            for f in FPS_SHOPS:
                if f["id"] == "FPS-4102":
                    f["trust_score"] = 21.0
                    f["risk_level"] = "CRITICAL"
                    f["inspection_status"] = "FLYING_SQUAD_DISPATCHED"

            return {
                "scenario": scenario_type,
                "title": "Severe Black Market Diversion Scenario",
                "description": "Truck MH-31-8820 diverts off state highway corridor to unauthorized private mill in Pardi.",
                "disruption_impact": {
                    "grain_at_risk_mt": 4.5,
                    "affected_beneficiaries": 2150,
                    "fraud_value_inr": 180000
                },
                "sentinel_ai_response": {
                    "detection_latency": "1.8 seconds post-geofence breach",
                    "automated_actions_taken": [
                        "GPS Geofence Breach Flagged (Corridor Variance > 3.2 km)",
                        "Electronic Seal Tamper Alert Broadcasted to District Supply Officer",
                        "POS Device POS-NGP-4102 Temporarily Quota-Locked",
                        "Smart Re-routing: Allocated 4.5 MT buffer reserve from Central Depot Ajni to verified FPS-4103"
                    ],
                    "grain_saved_mt": 4.5,
                    "citizen_impact_mitigated": "100% beneficiaries auto-redirected to verified alternate shop FPS-4103"
                }
            }

        elif scenario_type == "GHOST_CARD_SWEEP":
            for f in FPS_SHOPS:
                if f["id"] == "FPS-4106":
                    f["trust_score"] = 31.0
                    f["risk_level"] = "CRITICAL"
                    f["tags"].append("Active Biometric Exploit Flag")

            return {
                "scenario": scenario_type,
                "title": "Midnight Ghost Ration Card Sweep Burst",
                "description": "Dealer attempts 65 fake transactions between 02:00 AM - 04:00 AM using cloned barcodes.",
                "disruption_impact": {
                    "grain_at_risk_mt": 2.2,
                    "affected_beneficiaries": 1280,
                    "fraud_value_inr": 88000
                },
                "sentinel_ai_response": {
                    "detection_latency": "Real-time at Transaction #3",
                    "automated_actions_taken": [
                        "Off-hours transaction velocity anomaly triggered by Isolation Forest",
                        "Aadhaar de-duplication engine blocked 48 non-biometric OTP transactions",
                        "Dealer POS device remotely disabled",
                        "Automated SMS alerts sent to genuine cardholders"
                    ],
                    "grain_saved_mt": 2.2,
                    "citizen_impact_mitigated": "False transactions revoked, quotas safely restored"
                }
            }

        elif scenario_type == "MONSOON_ROUTE_BLOCK":
            return {
                "scenario": scenario_type,
                "title": "Monsoon Highway Flood Disruption & Dynamic Re-Routing",
                "description": "NH-53 Eastern Bridge flooded; primary delivery route to Kamptee Silo blocked.",
                "disruption_impact": {
                    "grain_at_risk_mt": 18.0,
                    "delayed_shops_count": 4,
                    "expected_stockout_hours": 12
                },
                "sentinel_ai_response": {
                    "detection_latency": "Instant GIS Weather & Traffic Layer integration",
                    "automated_actions_taken": [
                        "Identified flood choke point on GIS Leaflet Network",
                        "Calculated alternative green corridor via Ring Road-4 (+14 mins transit time)",
                        "Sent dynamic turn-by-turn route dispatch to truck in-cabin navigation",
                        "Prevented stockout across 4 rural Fair Price Shops"
                    ],
                    "grain_saved_mt": 18.0,
                    "citizen_impact_mitigated": "Zero ration distribution delay"
                }
            }

        elif scenario_type == "RESET_NORMAL":
            for t in TRUCKS:
                if t["id"] == "TRK-MH31-8820":
                    t["status"] = "ON_ROUTE_NORMAL"
                    t["geofence_breach"] = False
                    t["seal_status"] = "E-LOCK_INTACT"
                    t["speed_kmh"] = 34
                    t["deviation_duration_min"] = 0
                    t["current_estimated_weight_mt"] = 12.0
                    t["anomaly_reason"] = None
            for f in FPS_SHOPS:
                if f["id"] == "FPS-4102":
                    f["trust_score"] = 24.2
                    f["risk_level"] = "CRITICAL"
                    f["inspection_status"] = "FLYING_SQUAD_RECOMMENDED"

            return {
                "scenario": scenario_type,
                "title": "Environment Reset",
                "description": "Telemetry and simulation state reset to default Nagpur operational parameters.",
                "status": "SUCCESS"
            }

        return {"error": f"Unknown scenario type '{scenario_type}'"}

# Sync step: 163

# Sync step: 188

# Sync step: 213

# Sync step: 237

# Sync step: 269

# Sync step: 317

# Sync step: 355

# Sync step: 383

# Sync step: 163

# Sync step: 188

# Sync step: 213

# Sync step: 237
